<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Kendaraan;

class KendaraanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'nopol_kendaraan' => 'D 1841 D',
                'merk_type' => 'Toyota Kijang Innova 2.0 V',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2006,
                'nomor_rangka' => 'MHFXW43G764030762',
                'nomor_mesin' => '1TR6319485',
                'penggunaan' => 'Fakultas Hukum',
            ],
            [
                'nopol_kendaraan' => 'D 1814 A',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2005,
                'nomor_rangka' => 'MHFXW42G152040991',
                'nomor_mesin' => '1TR6126338',
                'penggunaan' => 'Fakultas Hukum',
            ],
            [
                'nopol_kendaraan' => 'D 1737 D',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2006,
                'nomor_rangka' => 'MHFFMREK36K013538',
                'nomor_mesin' => 'DB51267',
                'penggunaan' => 'Fakultas Hukum',
            ],
            [
                'nopol_kendaraan' => 'D 1131 F',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2007,
                'nomor_rangka' => 'MHFM1BA3J7K066027',
                'nomor_mesin' => 'DC57433',
                'penggunaan' => 'Fakultas Hukum',
            ],
            [
                'nopol_kendaraan' => 'Z 1061 BC',
                'merk_type' => 'Suzuki Ertiga',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MHYKZE81SHJ324319',
                'nomor_mesin' => 'K14BT1262447',
                'penggunaan' => 'Fakultas Hukum',
            ],
            // Data baru dimulai di sini
            [
                'nopol_kendaraan' => 'D 1876 A',
                'merk_type' => 'Toyota Kijang KF81 Krista',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2004,
                'nomor_rangka' => 'MHF11UF8140042553',
                'nomor_mesin' => '1RZ7042567',
                'penggunaan' => 'Fakultas Ekonomi dan Bisnis',
            ],
            [
                'nopol_kendaraan' => 'D 1814 B',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2005,
                'nomor_rangka' => 'MHFXW42G552040704',
                'nomor_mesin' => '1TR-6125085',
                'penggunaan' => 'Fakultas Ekonomi dan Bisnis',
            ],
            [
                'nopol_kendaraan' => 'D 1815 A',
                'merk_type' => 'Toyota Kijang Innova 2.0 E',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2005,
                'nomor_rangka' => 'MHFXW41G650010155',
                'nomor_mesin' => '1TR6126774',
                'penggunaan' => 'Fakultas Ekonomi dan Bisnis',
            ],
            [
                'nopol_kendaraan' => 'D 1835 C',
                'merk_type' => 'Toyota Kijang Innova 2.0 E',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2005,
                'nomor_rangka' => 'MHFXW41G150012198',
                'nomor_mesin' => '1TR-6171173',
                'penggunaan' => 'Fakultas Ekonomi dan Bisnis',
            ],
            [
                'nopol_kendaraan' => 'D 1742 D',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2006,
                'nomor_rangka' => 'MHFXW42G062059288',
                'nomor_mesin' => 'ITR6204841',
                'penggunaan' => 'Fakultas Ekonomi dan Bisnis',
            ],
            [
                'nopol_kendaraan' => 'D 1229 C',
                'merk_type' => 'Suzuki Grand Vitara JLX',
                'jenis_kendaraan' => 'SUV',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2007,
                'nomor_rangka' => 'MHYJTE54V7J703918',
                'nomor_mesin' => 'J20AID209906',
                'penggunaan' => 'Fakultas Ekonomi dan Bisnis',
            ],
            [
                'nopol_kendaraan' => 'D 1792 F',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2011,
                'nomor_rangka' => 'MHFXW42G9B2194845',
                'nomor_mesin' => '1TR7144309',
                'penggunaan' => 'Fakultas Ekonomi dan Bisnis',
            ],
            [
                'nopol_kendaraan' => 'D 7097 AT',
                'merk_type' => 'Isuzu NLR 55B',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2018,
                'nomor_rangka' => 'MHCNLR55EJJ081396',
                'nomor_mesin' => 'M081396',
                'penggunaan' => 'Fakultas Ekonomi dan Bisnis',
            ],
            [
                'nopol_kendaraan' => 'D 1129 F',
                'merk_type' => 'Toyota Kijang Innova 2.0 V',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2007,
                'nomor_rangka' => 'MHFXW43G774036644',
                'nomor_mesin' => '1TR6464469',
                'penggunaan' => 'Fakultas Kedokteran',
            ],
            [
                'nopol_kendaraan' => 'D 1097 F',
                'merk_type' => 'Suzuki APV DLX',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2007,
                'nomor_rangka' => 'MHYGDN41V7J158157',
                'nomor_mesin' => 'G15AID162023',
                'penggunaan' => 'Fakultas Kedokteran',
            ],
            [
                'nopol_kendaraan' => 'D 1550 JL',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2007,
                'nomor_rangka' => 'MHFM1BA3J7K046280',
                'nomor_mesin' => 'DC25032',
                'penggunaan' => 'Fakultas Kedokteran',
            ],
            [
                'nopol_kendaraan' => 'D 1552 JL',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2007,
                'nomor_rangka' => 'MHFXW42G372094019',
                'nomor_mesin' => 'ITR6393994',
                'penggunaan' => 'Fakultas Kedokteran',
            ],
            [
                'nopol_kendaraan' => 'D 7073 C',
                'merk_type' => 'KIA Pregio SE',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2010,
                'nomor_rangka' => 'PNAKF5S03AG001981',
                'nomor_mesin' => 'J2549138',
                'penggunaan' => 'Fakultas Kedokteran',
            ],
            [
                'nopol_kendaraan' => 'D 1096 E',
                'merk_type' => 'Toyota Avanza 1.5 Veloz',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2012,
                'nomor_rangka' => 'MHKM1CA4JCK006979',
                'nomor_mesin' => 'DCS1125',
                'penggunaan' => 'Fakultas Kedokteran',
            ],
            [
                'nopol_kendaraan' => 'D 1412 AKT',
                'merk_type' => 'Toyota Kijang Zenix Q 2.0 AT HV',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2023,
                'nomor_rangka' => 'MHFABBAA3P0408542',
                'nomor_mesin' => 'M20ANA88560',
                'penggunaan' => 'Fakultas Kedokteran',
            ],
            [
                'nopol_kendaraan' => 'D 7458 AT',
                'merk_type' => 'Toyota Hiace Premio 2.8 MT',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2023,
                'nomor_rangka' => 'JTF2A9CPXP6004185',
                'nomor_mesin' => '1GD9251566',
                'penggunaan' => 'Fakultas Kedokteran',
            ],
            [
                'nopol_kendaraan' => 'D 1203 F',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2008,
                'nomor_rangka' => 'MHFXW42G282115427',
                'nomor_mesin' => '1TR6551939',
                'penggunaan' => 'FMIPA',
            ],
            [
                'nopol_kendaraan' => 'D 1695 F',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2010,
                'nomor_rangka' => 'MHFM1BA3JAK725241',
                'nomor_mesin' => 'DG66154',
                'penggunaan' => 'FMIPA',
            ],
            [
                'nopol_kendaraan' => 'D 1831 D',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2006,
                'nomor_rangka' => 'MHFN1BA3J6K011506',
                'nomor_mesin' => 'DB71960',
                'penggunaan' => 'Fakultas Pertanian',
            ],
            [
                'nopol_kendaraan' => 'D 1327 F',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2009,
                'nomor_rangka' => 'MHFM1BA3J9K705094',
                'nomor_mesin' => 'DB86000',
                'penggunaan' => 'Fakultas Pertanian',
            ],
            [
                'nopol_kendaraan' => 'D 1167 F',
                'merk_type' => 'Toyota Avanza 1.5 S',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2007,
                'nomor_rangka' => 'MHFM1CA4J7K007359',
                'nomor_mesin' => 'DAF8963',
                'penggunaan' => 'Fakultas Kedokteran Gigi',
            ],
            [
                'nopol_kendaraan' => 'D 1458 F',
                'merk_type' => 'Toyota Avanza 1.5 S',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2010,
                'nomor_rangka' => 'MHFM1CA4JAK032644',
                'nomor_mesin' => 'DBM6325',
                'penggunaan' => 'Fakultas Kedokteran Gigi',
            ],
            [
                'nopol_kendaraan' => 'D 9948 A',
                'merk_type' => 'Isuzu Panther TBR 54',
                'jenis_kendaraan' => 'Ambulance',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2010,
                'nomor_rangka' => 'MHCTBR54BAK154880',
                'nomor_mesin' => 'E154880',
                'penggunaan' => 'Fakultas Kedokteran Gigi',
            ],
            [
                'nopol_kendaraan' => 'D 1827 A',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2010,
                'nomor_rangka' => 'MHFM1BA3JAK283183',
                'nomor_mesin' => 'DG74940',
                'penggunaan' => 'Fakultas Ilmu Budaya',
            ],
            [
                'nopol_kendaraan' => 'D 1885 D',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2007,
                'nomor_rangka' => 'MHFXW42G972094476',
                'nomor_mesin' => '1TR6396216',
                'penggunaan' => 'Fakultas Ilmu Budaya',
            ],
            [
                'nopol_kendaraan' => 'D 1806 A',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2005,
                'nomor_rangka' => 'MHFXW42G152037976',
                'nomor_mesin' => '1TR6112868',
                'penggunaan' => 'FISIP',
            ],
            [
                'nopol_kendaraan' => 'D 1806 B',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2005,
                'nomor_rangka' => 'MHFXW42G852036792',
                'nomor_mesin' => '1TR6107212',
                'penggunaan' => 'FISIP',
            ],
            [
                'nopol_kendaraan' => 'D 1833 D',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2006,
                'nomor_rangka' => 'MHFM1BA3J6K012826',
                'nomor_mesin' => 'DB73989',
                'penggunaan' => 'FISIP',
            ],
            [
                'nopol_kendaraan' => 'Z 365 A',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2006,
                'nomor_rangka' => 'MHFM1BA3J6K003566',
                'nomor_mesin' => 'DB60076',
                'penggunaan' => 'Fakultas Psikologi',
            ],
            [
                'nopol_kendaraan' => 'D 1531 B',
                'merk_type' => 'Toyota Avanza 1.5 S',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2011,
                'nomor_rangka' => 'MHFM1CA44JBK056530',
                'nomor_mesin' => 'DCF7363',
                'penggunaan' => 'Fakultas Psikologi',
            ],
            [
                'nopol_kendaraan' => 'D 1202 F',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2008,
                'nomor_rangka' => 'MHFXW42G182118836',
                'nomor_mesin' => 'ITR6576160',
                'penggunaan' => 'Fakultas Peternakan',
            ],
            [
                'nopol_kendaraan' => 'D 1814 F',
                'merk_type' => 'Toyota Avanza 1.5 S',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2011,
                'nomor_rangka' => 'MHFM1CA4JBK053750',
                'nomor_mesin' => 'DCD1529',
                'penggunaan' => 'Fakultas Peternakan',
            ],
            [
                'nopol_kendaraan' => 'D 8440 A',
                'merk_type' => 'Toyota Kijang KF60 Long',
                'jenis_kendaraan' => 'Pick Up',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2004,
                'nomor_rangka' => 'MHF31KF6040030681',
                'nomor_mesin' => '7K0710394',
                'penggunaan' => 'Fakultas Peternakan',
            ],
            [
                'nopol_kendaraan' => 'D 1463 A',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2004,
                'nomor_rangka' => 'MHFXW42G542011217',
                'nomor_mesin' => '1TR6023161',
                'penggunaan' => 'Fakultas Ilmu Komunikasi',
            ],
            [
                'nopol_kendaraan' => 'D 1022 D',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2006,
                'nomor_rangka' => 'MHFXW42G062059209',
                'nomor_mesin' => '1TR6204713',
                'penggunaan' => 'Fakultas Ilmu Komunikasi',
            ],
            [
                'nopol_kendaraan' => 'D 1096 F',
                'merk_type' => 'Suzuki APV DLX',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2007,
                'nomor_rangka' => 'MHYGDN41V7J157952',
                'nomor_mesin' => 'G15AID161841',
                'penggunaan' => 'Fakultas Ilmu Komunikasi',
            ],
            [
                'nopol_kendaraan' => 'D 7132 AU',
                'merk_type' => 'Toyota Hiace Commuter MT',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Putih',
                'tahun_pembuatan' => 2024,
                'nomor_rangka' => 'JTFST22PXR0047904',
                'nomor_mesin' => '1KDB194842',
                'penggunaan' => 'Fakultas Ilmu Komunikasi',
            ],
            [
                'nopol_kendaraan' => 'Z 1396 CJ',
                'merk_type' => 'Daihatsu Xenia Attivo',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2012,
                'nomor_rangka' => 'MHKV1BA2JCKO23362',
                'nomor_mesin' => 'DL22928',
                'penggunaan' => 'Fakultas Keperawatan',
            ],
            [
                'nopol_kendaraan' => 'D 1128 F',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2007,
                'nomor_rangka' => 'MHFM1BA3J7K066803',
                'nomor_mesin' => 'DC58629',
                'penggunaan' => 'Fakultas Keperawatan',
            ],
            [
                'nopol_kendaraan' => 'D 1130 F',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2007,
                'nomor_rangka' => 'MHFM1BA3J7K066514',
                'nomor_mesin' => 'DC58061',
                'penggunaan' => 'Fakultas Keperawatan',
            ],
            [
                'nopol_kendaraan' => 'D 1132 F',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2007,
                'nomor_rangka' => 'MHFM1BA3J7K066163',
                'nomor_mesin' => 'DC57656',
                'penggunaan' => 'FPIK',
            ],
            [
                'nopol_kendaraan' => 'D 1416 F',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2009,
                'nomor_rangka' => 'MHFM1BA3J9K188872',
                'nomor_mesin' => 'DE69697',
                'penggunaan' => 'FPIK',
            ],
            [
                'nopol_kendaraan' => 'D 1026 F',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2007,
                'nomor_rangka' => 'MHFM1BA3J7K033145',
                'nomor_mesin' => 'DC04950',
                'penggunaan' => 'FTIP',
            ],
            [
                'nopol_kendaraan' => 'D 1322 F',
                'merk_type' => 'Toyota Avanza 1.5 S',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2009,
                'nomor_rangka' => 'MHFM1CA4J9K019507',
                'nomor_mesin' => 'DBD3786',
                'penggunaan' => 'Fakultas Farmasi',
            ],
            [
                'nopol_kendaraan' => 'D 1324 F',
                'merk_type' => 'Toyota Avanza 1.5 S',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2009,
                'nomor_rangka' => 'MHFM1CA4J9K019621',
                'nomor_mesin' => 'DBD4354',
                'penggunaan' => 'Fakultas Farmasi',
            ],
            [
                'nopol_kendaraan' => 'D 1321 F',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2009,
                'nomor_rangka' => 'MHFM1BA3J9K138352',
                'nomor_mesin' => 'DD83873',
                'penggunaan' => 'Fakultas Teknik Geologi',
            ],
            [
                'nopol_kendaraan' => 'D 1697 F',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2010,
                'nomor_rangka' => 'MHFM1BA3JAK725257',
                'nomor_mesin' => 'DG71982',
                'penggunaan' => 'Fakultas Teknik Geologi',
            ],
            [
                'nopol_kendaraan' => 'D 1459 F',
                'merk_type' => 'Toyota Avanza 1.5 S',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2010,
                'nomor_rangka' => 'MHFM1CA4JAK032803',
                'nomor_mesin' => 'DBM7103',
                'penggunaan' => 'Sekolah Pasca Sarjana',
            ],
            [
                'nopol_kendaraan' => 'D 1740 D',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2006,
                'nomor_rangka' => 'MHFXW42G562066754',
                'nomor_mesin' => 'ITR6255173',
                'penggunaan' => 'MWA',
            ],
            [
                'nopol_kendaraan' => 'D 1 DU',
                'merk_type' => 'Hyundai Palisade',
                'jenis_kendaraan' => 'SUV',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2021,
                'nomor_rangka' => 'MHFGW8EM2H1018338',
                'nomor_mesin' => '1TRA400658',
                'penggunaan' => 'Rektor',
            ],
            [
                'nopol_kendaraan' => 'D 1320 F',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2009,
                'nomor_rangka' => 'MHFXW42G592134250',
                'nomor_mesin' => 'ITRE711137',
                'penggunaan' => 'Senat Akademik',
            ],
            [
                'nopol_kendaraan' => 'D 1114 E',
                'merk_type' => 'Toyota Kijang Innova 2.0 V',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2012,
                'nomor_rangka' => 'MHFXW43G5C4065084',
                'nomor_mesin' => '1TR7289464',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'Z 7347 AA',
                'merk_type' => 'Isuzu NKR 55 CO E2 1',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2014,
                'nomor_rangka' => 'MHCNKR55HEJ057840',
                'nomor_mesin' => 'M057840',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'Z 7363 AA',
                'merk_type' => 'Isuzu NKR 55 CO E2 1',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2015,
                'nomor_rangka' => 'MHCNKR55HFJ066140',
                'nomor_mesin' => 'M066140',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'Z 7364 AA',
                'merk_type' => 'Isuzu NKR 55 CO E2 1',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2015,
                'nomor_rangka' => 'MHCNHR55EPJ065245',
                'nomor_mesin' => 'M065245',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'Z 8101 CA',
                'merk_type' => 'Isuzu Panther TBR 54',
                'jenis_kendaraan' => 'Blind Van',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2016,
                'nomor_rangka' => 'MHCTBR54FGK174637',
                'nomor_mesin' => 'E174637',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7039 FB',
                'merk_type' => 'Isuzu NLR 55B LX',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MHCNLR55HHJ075756',
                'nomor_mesin' => 'M075756',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7040 FB',
                'merk_type' => 'Isuzu NLR 55B LX',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MHCNLR55HHJ075828',
                'nomor_mesin' => 'M075828',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7041 FB',
                'merk_type' => 'Isuzu NLR 55B LX',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MHCNLR55HHJ075829',
                'nomor_mesin' => 'M075829',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7042 FB',
                'merk_type' => 'Isuzu NLR 55B LX',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MHCNLR55HHJ075830',
                'nomor_mesin' => 'M075830',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7043 FB',
                'merk_type' => 'Isuzu NLR 55B LX',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MHCNLR55HHJ076144',
                'nomor_mesin' => 'M076144',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7044 FB',
                'merk_type' => 'Isuzu NLR 55B LX',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MHCNLR55HHJ076146',
                'nomor_mesin' => 'M076146',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7045 FB',
                'merk_type' => 'Isuzu NLR 55B LX',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MHCNLR55HHJ076150',
                'nomor_mesin' => 'M076150',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7046 FB',
                'merk_type' => 'Isuzu NLR 55B LX',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MHCNLR55HHJ076151',
                'nomor_mesin' => 'M076151',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'Z 7404 AA',
                'merk_type' => 'Isuzu NLR 55B LX',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MHCNLR55HJJ078724',
                'nomor_mesin' => 'M078724',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7411 AT',
                'merk_type' => 'Isuzu NLR 85U HBYIN1',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2023,
                'nomor_rangka' => 'MHCNLR85HPJ003254',
                'nomor_mesin' => '238C24',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7412 AT',
                'merk_type' => 'Isuzu NLR 85U HBYIN1',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2023,
                'nomor_rangka' => 'MHCNLR85HPJ003064',
                'nomor_mesin' => '236V18',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7489 AT',
                'merk_type' => 'Isuzu NLR 85U HBYIN1',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2023,
                'nomor_rangka' => 'MHCNLR85HPJ003257',
                'nomor_mesin' => '238G38',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7088 AU',
                'merk_type' => 'Isuzu NLR 85U HBYIN1',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2023,
                'nomor_rangka' => 'MHCNLR85HPJ003037',
                'nomor_mesin' => '236K88',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'Z 7417 AA',
                'merk_type' => 'Isuzu NLR 85U HBYIN1',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2024,
                'nomor_rangka' => 'MHCNLR85HRJ005289',
                'nomor_mesin' => '279V58',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'Z 7419 AA',
                'merk_type' => 'Isuzu NLR 85U HBYIN1',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Putih',
                'tahun_pembuatan' => 2024,
                'nomor_rangka' => 'MHCNLR85HRJ005792',
                'nomor_mesin' => '287C03',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1659 B',
                'merk_type' => 'Suzuki Carry Futura ST 150',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2003,
                'nomor_rangka' => 'MHYESL4153J543656',
                'nomor_mesin' => 'G15AIA543656',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 8128 B',
                'merk_type' => 'Suzuki Carry Futura ST 150',
                'jenis_kendaraan' => 'Pick Up',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2005,
                'nomor_rangka' => 'MHYESL4155J169059',
                'nomor_mesin' => 'G15AA169007',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1475 C',
                'merk_type' => 'Suzuki Carry Futura ST 150',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2003,
                'nomor_rangka' => 'MHYESL4153J543855',
                'nomor_mesin' => 'G15AIA543855',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1442 C',
                'merk_type' => 'Suzuki Carry Futura ST 150',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2003,
                'nomor_rangka' => 'MHYESL4153J543787',
                'nomor_mesin' => 'G15AIA543787',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1478 C',
                'merk_type' => 'Suzuki Carry Futura ST 150',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2003,
                'nomor_rangka' => 'MHYESL4153J543390',
                'nomor_mesin' => 'G15AIA543390',
                'penggunaan' => 'Direktorat Perencanaan dan Sistem Informasi',
            ],
            [
                'nopol_kendaraan' => 'D 1240 D',
                'merk_type' => 'Isuzu Panther TBR 541',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2006,
                'nomor_rangka' => 'MHCTBR54F6K279563',
                'nomor_mesin' => 'E279563',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1201 F',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2008,
                'nomor_rangka' => 'MHFXW42G982119071',
                'nomor_mesin' => '1TR6578669',
                'penggunaan' => 'FTIP',
            ],
            [
                'nopol_kendaraan' => 'D 1204 F',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2008,
                'nomor_rangka' => 'MHFXW42G582119150',
                'nomor_mesin' => '1TR6579054',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1332 F',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2009,
                'nomor_rangka' => 'MHFXW42G892136901',
                'nomor_mesin' => '1TR6736209',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1275 EG',
                'merk_type' => 'Hyundai H-1',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2010,
                'nomor_rangka' => 'MHXWF31RMAJ100555',
                'nomor_mesin' => 'G4KGAA468940',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 8567 C',
                'merk_type' => 'Isuzu NKR 71 E2 2',
                'jenis_kendaraan' => 'Truk Boks',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2010,
                'nomor_rangka' => 'MHCNK71LYAJ020129',
                'nomor_mesin' => 'B020129',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7093 C',
                'merk_type' => 'Hino WU342R-HKMRJD3BL',
                'jenis_kendaraan' => 'Medium Bus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2011,
                'nomor_rangka' => 'MJEC1JG43B5036485',
                'nomor_mesin' => 'W04DTRJ40252',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1716 F',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2010,
                'nomor_rangka' => 'MHFXW42G8A2177291',
                'nomor_mesin' => '1TR7030617',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7158 C',
                'merk_type' => 'Hino WU342R-HKMRJD3BL',
                'jenis_kendaraan' => 'Medium Bus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2013,
                'nomor_rangka' => 'MJEC1JG43D5093688',
                'nomor_mesin' => 'W04DTRJ90430',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7163 C',
                'merk_type' => 'Hino WU342R-HKMRJD3BL',
                'jenis_kendaraan' => 'Medium Bus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2013,
                'nomor_rangka' => 'MJEC1JG43D5093687',
                'nomor_mesin' => 'W04DTRJ90429',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'Z 8237 A',
                'merk_type' => 'Hino WU342R-HKMRJD3',
                'jenis_kendaraan' => 'Truk Tangki',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2013,
                'nomor_rangka' => 'MJEC1JG43D5091098',
                'nomor_mesin' => 'W04DTRJ88180',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7095 BA',
                'merk_type' => 'Toyota Hiace Commuter MT',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'JTFSS2P2H0164586',
                'nomor_mesin' => '2KDA933162',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'Z 7384 AA',
                'merk_type' => 'Isuzu NLR 55B',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2019,
                'nomor_rangka' => 'MHCNLR55EKJ082925',
                'nomor_mesin' => 'M082925',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'Z 9923 AA',
                'merk_type' => 'Suzuki APV DLX',
                'jenis_kendaraan' => 'Ambulance',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2019,
                'nomor_rangka' => 'MHYGDN42VKJ402169',
                'nomor_mesin' => 'G15AID434260',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1698 F',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2010,
                'nomor_rangka' => 'MHFXW42G0A2177611',
                'nomor_mesin' => '1TR7032999',
                'penggunaan' => 'PSDKU Pangandaran',
            ],
            [
                'nopol_kendaraan' => 'D 1614 B',
                'merk_type' => 'Suzuki Carry Futura ST 130',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2003,
                'nomor_rangka' => 'MHYESL4153J543759',
                'nomor_mesin' => 'G15AIA543759',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'Z 8236 A',
                'merk_type' => 'Hino WU342R-HKMRJD3',
                'jenis_kendaraan' => 'Dump Truck',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2013,
                'nomor_rangka' => 'MJEC1JG43D5084586',
                'nomor_mesin' => 'W04DTRJ82854',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 8576 FR',
                'merk_type' => 'Isuzu Traga PHR 54 C BB',
                'jenis_kendaraan' => 'Pick Up',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2022,
                'nomor_rangka' => 'MHCPHR54CNJ432129',
                'nomor_mesin' => 'E432129',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 8577 FR',
                'merk_type' => 'Isuzu Traga PHR 54 C BB',
                'jenis_kendaraan' => 'Pick Up',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2022,
                'nomor_rangka' => 'MHCPHR54CNJ432117',
                'nomor_mesin' => 'E432117',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 8578 FR',
                'merk_type' => 'Isuzu Traga PHR 54 C BB',
                'jenis_kendaraan' => 'Pick Up',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2022,
                'nomor_rangka' => 'MHCPHR54CNJ432128',
                'nomor_mesin' => 'E432128',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 8579 FR',
                'merk_type' => 'Isuzu Traga PHR 54 C BB',
                'jenis_kendaraan' => 'Pick Up',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2022,
                'nomor_rangka' => 'MHCPHR54CNJ432172',
                'nomor_mesin' => 'E432172',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 8580 FR',
                'merk_type' => 'Isuzu Traga PHR 54 C BB',
                'jenis_kendaraan' => 'Pick Up',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2022,
                'nomor_rangka' => 'MHCPHR54CNJ432132',
                'nomor_mesin' => 'E432132',
                'penggunaan' => 'PSDKU Pangandaran',
            ],
            [
                'nopol_kendaraan' => 'Z 9903 CH',
                'merk_type' => 'Hino WU342RHRMLHD8110SDBL',
                'jenis_kendaraan' => 'Ambulance',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2020,
                'nomor_rangka' => 'MJEC1JG41L5192033',
                'nomor_mesin' => 'W04DTPJ85383',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1294 F',
                'merk_type' => 'Mitsubishi L300',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2008,
                'nomor_rangka' => 'MHML0WY398K001647',
                'nomor_mesin' => '4D56CD13084',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 8801 FS',
                'merk_type' => 'Isuzu NMR81U-HAY1N465 4X2 MT',
                'jenis_kendaraan' => 'Mobil Crane',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2022,
                'nomor_rangka' => 'MHCNMR81HNJ103968',
                'nomor_mesin' => 'G103968',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1549 GH',
                'merk_type' => 'Toyota Avanza 1.5 Veloz',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MHKM5FB4JHK015328',
                'nomor_mesin' => '2NRF625637',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1002 DUP',
                'merk_type' => 'Toyota Kijang Innova 2.0 V',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MHFGW8EM2H1018338',
                'nomor_mesin' => '1TR A400658',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1003 DUP',
                'merk_type' => 'Toyota Kijang Innova 2.0 V',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MHFGW8EM6H1018391',
                'nomor_mesin' => '1TR A401972',
                'penggunaan' => 'PSDKU Pangandaran',
            ],
            [
                'nopol_kendaraan' => 'D 1004 DUP',
                'merk_type' => 'Toyota Kijang Innova 2.0 V',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MHFGW8EMXH1018278',
                'nomor_mesin' => '1TR A399241',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7001 DU',
                'merk_type' => 'Toyota Hiace Commuter MT',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'JTFSS22P5H0168115',
                'nomor_mesin' => '2KDA943710',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7002 DU',
                'merk_type' => 'Toyota Hiace Commuter MT',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'JTFSS22P0H0167776',
                'nomor_mesin' => '2KDA939965',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7003 DU',
                'merk_type' => 'Toyota Hiace Commuter MT',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'JTFSS22P5H0167210',
                'nomor_mesin' => '2KDA940924',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7004 DU',
                'merk_type' => 'Hino WU342R-HKMRJD3BL',
                'jenis_kendaraan' => 'Medium Bus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MJEC1JG43H5154111',
                'nomor_mesin' => 'W04DTRR43942',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7005 DU',
                'merk_type' => 'Hino WU342R-HKMRJD3BL',
                'jenis_kendaraan' => 'Medium Bus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MJEC1JG43H5154112',
                'nomor_mesin' => 'W04DTRR43943',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7006 DU',
                'merk_type' => 'Hino RN8JSKASJJ/RN285',
                'jenis_kendaraan' => 'Big Bus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MJERN8JSKHJS12983',
                'nomor_mesin' => 'J08EVTJ11381',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1601 HQ',
                'merk_type' => 'Toyota Avanza 1.5 Veloz',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2019,
                'nomor_rangka' => 'MHKM5FB4JKK025187',
                'nomor_mesin' => '2NRF887911',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 7010 AT',
                'merk_type' => 'Isuzu NLR 55B LX',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2019,
                'nomor_rangka' => 'MHCNLR55HKJ085097',
                'nomor_mesin' => 'M085097',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 8025 FK',
                'merk_type' => 'Suzuki AEV415P CL',
                'jenis_kendaraan' => 'Pick Up',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2019,
                'nomor_rangka' => 'MHYHDC61TKJ109871',
                'nomor_mesin' => 'KI5BT1053945',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 8382 FD',
                'merk_type' => 'Hino WU342R-HKMRJD3',
                'jenis_kendaraan' => 'Dump Truck',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2017,
                'nomor_rangka' => 'MJEC1JG43H5156582',
                'nomor_mesin' => 'W04DTRR47403',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 8027 FK',
                'merk_type' => 'SuzukiI AEV415P CL',
                'jenis_kendaraan' => 'Pick Up',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2019,
                'nomor_rangka' => 'MHYHDC61TKJ116574',
                'nomor_mesin' => 'KI5BT1071585',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1479 AJK',
                'merk_type' => 'Toyota Kijang Innova G Luxury',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2021,
                'nomor_rangka' => 'MHFJW8EM6M2392378',
                'nomor_mesin' => '1TRA901245',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1518 AKN',
                'merk_type' => 'Toyota Kijang Zenix V 2.0 AT',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2023,
                'nomor_rangka' => 'MHFAAAAA4N0003381',
                'nomor_mesin' => 'M20ANA10495',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1519 AKN',
                'merk_type' => 'Toyota Kijang Zenix V 2.0 AT',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2023,
                'nomor_rangka' => 'MHFAAAAA2N0002911',
                'nomor_mesin' => 'M20ANA07965',
                'penggunaan' => 'Direktorat Sarana Prasarana dan Manajemen Aset',
            ],
            [
                'nopol_kendaraan' => 'D 1728 A',
                'merk_type' => 'Toyota Kijang KF71',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2003,
                'nomor_rangka' => 'MHF11KF7130009789',
                'nomor_mesin' => '7K0636764',
                'penggunaan' => 'Laboratorium Sentral',
            ],
            [
                'nopol_kendaraan' => 'D 7138 AJ',
                'merk_type' => 'Isuzu NHR 55',
                'jenis_kendaraan' => 'Mikrobus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2001,
                'nomor_rangka' => 'MHCNH55EY1J001992',
                'nomor_mesin' => 'M001992',
                'penggunaan' => 'UPT Balai Kesehatan',
            ],
            [
                'nopol_kendaraan' => 'D 1496 B',
                'merk_type' => 'Toyota Kijang KF71',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2001,
                'nomor_rangka' => 'MHF11KF7110005819',
                'nomor_mesin' => '7K0450702',
                'penggunaan' => 'UPT Balai Kesehatan',
            ],
            [
                'nopol_kendaraan' => 'Z 9901 AB',
                'merk_type' => 'Toyota Hiace Commuter MT',
                'jenis_kendaraan' => 'Ambulance',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => 2021,
                'nomor_rangka' => 'JTFSS22P7M0196041',
                'nomor_mesin' => '2KDB095107',
                'penggunaan' => 'UPT Balai Kesehatan',
            ],
            [
                'nopol_kendaraan' => 'D 9926 AC',
                'merk_type' => 'Daihatsu Granmax',
                'jenis_kendaraan' => 'Ambulance',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2009,
                'nomor_rangka' => 'MHKB3BA1J9K001360',
                'nomor_mesin' => 'DD85788',
                'penggunaan' => 'RSGM',
            ],
            [
                'nopol_kendaraan' => 'D 1137 C',
                'merk_type' => 'Toyota Kijang KF83 LSX',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2000,
                'nomor_rangka' => 'MHF11TF83Y0029595',
                'nomor_mesin' => 'TK0387962',
                'penggunaan' => 'RSGM',
            ],
            [
                'nopol_kendaraan' => 'D 1379 ALO',
                'merk_type' => 'Suzuki XL7415F GL 4X2 MT',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Putih',
                'tahun_pembuatan' => 2024,
                'nomor_rangka' => 'MHYANC22SRJ101930',
                'nomor_mesin' => 'K15BT1611102',
                'penggunaan' => 'RSGM',
            ],
            [
                'nopol_kendaraan' => 'D 1832 D',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2006,
                'nomor_rangka' => 'MHFM1BA3J6K011775',
                'nomor_mesin' => 'DB72643',
                'penggunaan' => 'Koperasi Unpad',
            ],
            [
                'nopol_kendaraan' => 'D 1139 F',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2007,
                'nomor_rangka' => 'MHFXW42G172106197',
                'nomor_mesin' => '1TR6487154',
                'penggunaan' => 'Pusat Unggulan Lingkungan dan Ilmu Keberlanjutan (PULIK)',
            ],
            [
                'nopol_kendaraan' => 'D 1630 D',
                'merk_type' => 'Toyota Kijang Innova 2.0 E',
                'jenis_kendaraan' => 'Minibus',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => 2011,
                'nomor_rangka' => 'MHFXW41GXB0047625',
                'nomor_mesin' => '1TR7204506',
                'penggunaan' => 'Pusat Unggulan Lingkungan dan Ilmu Keberlanjutan (PULIK)',
            ],
        ];

        // Mendapatkan nopol_kendaraan yang sudah ada di database untuk menghindari duplikasi
        $existingNopol = Kendaraan::pluck('nopol_kendaraan')->toArray();

        // Menyaring data baru yang nopol_kendaraan-nya belum ada di database
        $filteredData = array_filter($data, function ($item) use ($existingNopol) {
            return !in_array($item['nopol_kendaraan'], $existingNopol);
        });

        // Memasukkan data ke database
        Kendaraan::insert($filteredData);
    }
}
